//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/* SPDX-License-Identifier: LGPL-2.1-or-later */

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	bluechi "github.com/engelmi/bluechi-server/pkg/apis/bluechi"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*BlueChiNode)(nil), (*bluechi.BlueChiNode)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BlueChiNode_To_bluechi_BlueChiNode(a.(*BlueChiNode), b.(*bluechi.BlueChiNode), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*bluechi.BlueChiNode)(nil), (*BlueChiNode)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_bluechi_BlueChiNode_To_v1alpha1_BlueChiNode(a.(*bluechi.BlueChiNode), b.(*BlueChiNode), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BlueChiSystem)(nil), (*bluechi.BlueChiSystem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BlueChiSystem_To_bluechi_BlueChiSystem(a.(*BlueChiSystem), b.(*bluechi.BlueChiSystem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*bluechi.BlueChiSystem)(nil), (*BlueChiSystem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_bluechi_BlueChiSystem_To_v1alpha1_BlueChiSystem(a.(*bluechi.BlueChiSystem), b.(*BlueChiSystem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BlueChiSystemList)(nil), (*bluechi.BlueChiSystemList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BlueChiSystemList_To_bluechi_BlueChiSystemList(a.(*BlueChiSystemList), b.(*bluechi.BlueChiSystemList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*bluechi.BlueChiSystemList)(nil), (*BlueChiSystemList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_bluechi_BlueChiSystemList_To_v1alpha1_BlueChiSystemList(a.(*bluechi.BlueChiSystemList), b.(*BlueChiSystemList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BlueChiSystemSpec)(nil), (*bluechi.BlueChiSystemSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BlueChiSystemSpec_To_bluechi_BlueChiSystemSpec(a.(*BlueChiSystemSpec), b.(*bluechi.BlueChiSystemSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*bluechi.BlueChiSystemSpec)(nil), (*BlueChiSystemSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_bluechi_BlueChiSystemSpec_To_v1alpha1_BlueChiSystemSpec(a.(*bluechi.BlueChiSystemSpec), b.(*BlueChiSystemSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_BlueChiNode_To_bluechi_BlueChiNode(in *BlueChiNode, out *bluechi.BlueChiNode, s conversion.Scope) error {
	out.Name = in.Name
	out.Status = bluechi.NodeStatus(in.Status)
	out.LastSeenTimestamp = in.LastSeenTimestamp
	return nil
}

// Convert_v1alpha1_BlueChiNode_To_bluechi_BlueChiNode is an autogenerated conversion function.
func Convert_v1alpha1_BlueChiNode_To_bluechi_BlueChiNode(in *BlueChiNode, out *bluechi.BlueChiNode, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlueChiNode_To_bluechi_BlueChiNode(in, out, s)
}

func autoConvert_bluechi_BlueChiNode_To_v1alpha1_BlueChiNode(in *bluechi.BlueChiNode, out *BlueChiNode, s conversion.Scope) error {
	out.Name = in.Name
	out.Status = NodeStatus(in.Status)
	out.LastSeenTimestamp = in.LastSeenTimestamp
	return nil
}

// Convert_bluechi_BlueChiNode_To_v1alpha1_BlueChiNode is an autogenerated conversion function.
func Convert_bluechi_BlueChiNode_To_v1alpha1_BlueChiNode(in *bluechi.BlueChiNode, out *BlueChiNode, s conversion.Scope) error {
	return autoConvert_bluechi_BlueChiNode_To_v1alpha1_BlueChiNode(in, out, s)
}

func autoConvert_v1alpha1_BlueChiSystem_To_bluechi_BlueChiSystem(in *BlueChiSystem, out *bluechi.BlueChiSystem, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_BlueChiSystemSpec_To_bluechi_BlueChiSystemSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = bluechi.BlueChiSystemStatus(in.Status)
	return nil
}

// Convert_v1alpha1_BlueChiSystem_To_bluechi_BlueChiSystem is an autogenerated conversion function.
func Convert_v1alpha1_BlueChiSystem_To_bluechi_BlueChiSystem(in *BlueChiSystem, out *bluechi.BlueChiSystem, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlueChiSystem_To_bluechi_BlueChiSystem(in, out, s)
}

func autoConvert_bluechi_BlueChiSystem_To_v1alpha1_BlueChiSystem(in *bluechi.BlueChiSystem, out *BlueChiSystem, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_bluechi_BlueChiSystemSpec_To_v1alpha1_BlueChiSystemSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = BlueChiSystemStatus(in.Status)
	return nil
}

// Convert_bluechi_BlueChiSystem_To_v1alpha1_BlueChiSystem is an autogenerated conversion function.
func Convert_bluechi_BlueChiSystem_To_v1alpha1_BlueChiSystem(in *bluechi.BlueChiSystem, out *BlueChiSystem, s conversion.Scope) error {
	return autoConvert_bluechi_BlueChiSystem_To_v1alpha1_BlueChiSystem(in, out, s)
}

func autoConvert_v1alpha1_BlueChiSystemList_To_bluechi_BlueChiSystemList(in *BlueChiSystemList, out *bluechi.BlueChiSystemList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]bluechi.BlueChiSystem)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_BlueChiSystemList_To_bluechi_BlueChiSystemList is an autogenerated conversion function.
func Convert_v1alpha1_BlueChiSystemList_To_bluechi_BlueChiSystemList(in *BlueChiSystemList, out *bluechi.BlueChiSystemList, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlueChiSystemList_To_bluechi_BlueChiSystemList(in, out, s)
}

func autoConvert_bluechi_BlueChiSystemList_To_v1alpha1_BlueChiSystemList(in *bluechi.BlueChiSystemList, out *BlueChiSystemList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]BlueChiSystem)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_bluechi_BlueChiSystemList_To_v1alpha1_BlueChiSystemList is an autogenerated conversion function.
func Convert_bluechi_BlueChiSystemList_To_v1alpha1_BlueChiSystemList(in *bluechi.BlueChiSystemList, out *BlueChiSystemList, s conversion.Scope) error {
	return autoConvert_bluechi_BlueChiSystemList_To_v1alpha1_BlueChiSystemList(in, out, s)
}

func autoConvert_v1alpha1_BlueChiSystemSpec_To_bluechi_BlueChiSystemSpec(in *BlueChiSystemSpec, out *bluechi.BlueChiSystemSpec, s conversion.Scope) error {
	out.Nodes = *(*bluechi.BlueChiNodes)(unsafe.Pointer(&in.Nodes))
	return nil
}

// Convert_v1alpha1_BlueChiSystemSpec_To_bluechi_BlueChiSystemSpec is an autogenerated conversion function.
func Convert_v1alpha1_BlueChiSystemSpec_To_bluechi_BlueChiSystemSpec(in *BlueChiSystemSpec, out *bluechi.BlueChiSystemSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlueChiSystemSpec_To_bluechi_BlueChiSystemSpec(in, out, s)
}

func autoConvert_bluechi_BlueChiSystemSpec_To_v1alpha1_BlueChiSystemSpec(in *bluechi.BlueChiSystemSpec, out *BlueChiSystemSpec, s conversion.Scope) error {
	out.Nodes = *(*BlueChiNodes)(unsafe.Pointer(&in.Nodes))
	return nil
}

// Convert_bluechi_BlueChiSystemSpec_To_v1alpha1_BlueChiSystemSpec is an autogenerated conversion function.
func Convert_bluechi_BlueChiSystemSpec_To_v1alpha1_BlueChiSystemSpec(in *bluechi.BlueChiSystemSpec, out *BlueChiSystemSpec, s conversion.Scope) error {
	return autoConvert_bluechi_BlueChiSystemSpec_To_v1alpha1_BlueChiSystemSpec(in, out, s)
}
