//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/* SPDX-License-Identifier: LGPL-2.1-or-later */

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&BlueChiSystem{}, func(obj interface{}) { SetObjectDefaults_BlueChiSystem(obj.(*BlueChiSystem)) })
	scheme.AddTypeDefaultingFunc(&BlueChiSystemList{}, func(obj interface{}) { SetObjectDefaults_BlueChiSystemList(obj.(*BlueChiSystemList)) })
	return nil
}

func SetObjectDefaults_BlueChiSystem(in *BlueChiSystem) {
	SetDefaults_BlueChiSystemSpec(&in.Spec)
}

func SetObjectDefaults_BlueChiSystemList(in *BlueChiSystemList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_BlueChiSystem(a)
	}
}
